name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Get Branch Name
        id: branch
        run: echo ::set-output name=branch::${GITHUB_REF#refs/heads/}

      - name: Install dependencies
        run : |
            sudo apt install python3-pip jq
      
      - name: Install Semgrep
        run: | 
            pip install semgrep

      - name: Install Gitleaks
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/download/v8.16.2/gitleaks_8.16.2_linux_x64.tar.gz
          tar -zxvf gitleaks_8.16.2_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/gitleaks

      - name: Run Semgrep Scan
        run: |
          semgrep --config=auto --json --output semgrep-results.json
          if grep -qE "(MEDIUM|HIGH|CRITICAL)" semgrep-results.json; then
            cat semgrep-results.json | jq  -c '[.results[] | {message: .extra.message , secret: .extra.lines , impact: .extra.metadata.impact}] | jq' >&2
            exit 1
          fi
        continue-on-error: false

      - name: Run Gitleaks Scan
        # Gitleaks will fail with "1" when secrets detected
        run: gitleaks detect --verbose --redact -f gitleaks-results.txt
        # Whether to continue if secrets got detected
        continue-on-error: false
