name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Get Branch Name
        id: branch
        run: echo ::set-output name=branch::${GITHUB_REF#refs/heads/}

      - name: Install Semgrep
        run: | 
            sudo apt install python3-pip
            pip install semgrep

      - name: Install Gitleaks
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/download/v8.16.2/gitleaks_8.16.2_linux_x64.tar.gz
          tar -zxvf gitleaks_8.16.2_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/gitleaks

      - name: Run Semgrep Scan
        run: |
          semgrep --config=auto > semgrep-results.txt
          if grep -qE "(HIGH|CRITICAL)" semgrep-results.txt; then
            grep -E "(HIGH|CRITICAL)" semgrep-results.txt >&2
            exit 1
          fi
        continue-on-error: true

      - name: Run Gitleaks Scan
        run: |
          gitleaks detect --verbose --redact > gitleaks-results.txt
          if grep -qE "(HIGH|CRITICAL)" gitleaks-results.txt; then
            grep -E "(HIGH|CRITICAL)" gitleaks-results.txt >&2
            exit 1
          fi
        continue-on-error: true
